/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete;

import java.util.ArrayList;

/**
 *
 * @author Ignacio
 */
public class FrameJuego extends javax.swing.JFrame {

    private boolean inicarPartida = false;
    DatosTablero datosTablero;
    private final int TABLERO_4 = 3;

    /**
     * Creates new form PanelGrafico
     */
    public FrameJuego() {
        initComponents();

        //Centramos la ventana
        setLocationRelativeTo(null);
        
        //Creamos el Objeto con los Datos del Fichero de Configuracion
        datosTablero = new DatosTablero();
        
        //Cargamos el ComboBox con los Nombres de los Tableros
        ArrayList<String> nombresTableros = datosTablero.getNombresTableros();        
        for(String nombreTablero:nombresTableros){
            jCBNombresTableros.addItem(nombreTablero);
        }
        //Seleccionamos por defecto el Tablero Nº 4
        jCBNombresTableros.setSelectedIndex(TABLERO_4);
        
        //Cargamos el Tablero
        reiniciarPartida();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBIniciar = new javax.swing.JButton();
        panelBotones = new paquete.PanelTablero();
        jBDeshacer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jCBNombresTableros = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBIniciar.setText("Iniciar Partida");
        jBIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIniciarActionPerformed(evt);
            }
        });

        panelBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBDeshacer.setText("Deshacer");
        jBDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeshacerActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar Movimientos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCBNombresTableros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBNombresTablerosActionPerformed(evt);
            }
        });

        jLabel1.setText("Tablero:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBDeshacer)
                        .addContainerGap(135, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBNombresTableros, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDeshacer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jCBNombresTableros, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIniciarActionPerformed
        
        //Si pulsa en Iniciar Partida -> Iniciamos la Partida
        if (!inicarPartida)
            iniciarPartida();
        //Si pulsa en Reiniciar Partida -> Creamos un Nuevo Panel
        else
            reiniciarPartida();
    }//GEN-LAST:event_jBIniciarActionPerformed

    private void iniciarPartida(){
        //Ponemos en Modo Iniciado
        inicarPartida = true;

        //Cambiamos el Texto del Boton
        jBIniciar.setText("Reiniciar");

        //Obtenemos el Nombre del Tablero Seleccionado
        String nombreTablero = jCBNombresTableros.getSelectedItem().toString();

        //Cargamos los Datos del Tablero Seleccionado
        panelBotones.inicializaTablero(datosTablero.getTablero(nombreTablero));

        //Activamos el Tablero
        panelBotones.setPanelActivo(true);
    }
    
    private void reiniciarPartida(){
        //Ponemos el Modo Reiniciado
        inicarPartida = false;

        //Obtenemos el Nombre del Tablero Seleccionado
        String nombreTablero = jCBNombresTableros.getSelectedItem().toString();

        //Reinicimos el Tablero
        panelBotones.reiniciarTablero(datosTablero.getTablero(nombreTablero));

        //Cambiamos el Texto del Boton
        jBIniciar.setText("Iniciar Partida");
    }
    
    private void jBDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeshacerActionPerformed
        //Deshacemos el Ultimo Movimiento Realizado
        panelBotones.deshacerMovimiento();
    }//GEN-LAST:event_jBDeshacerActionPerformed

    private void jCBNombresTablerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBNombresTablerosActionPerformed
        //Reiniciamos el Panel
        reiniciarPartida();
    }//GEN-LAST:event_jCBNombresTablerosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DatosXML datosXML = new DatosXML();
        datosXML.generaXML(panelBotones.getMovimientos());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameJuego().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDeshacer;
    private javax.swing.JButton jBIniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCBNombresTableros;
    private javax.swing.JLabel jLabel1;
    private paquete.PanelTablero panelBotones;
    // End of variables declaration//GEN-END:variables
}
